### PR TITLE
[#58] 🐛 - web Out of memory when trying to decompress a 17MB buffer

### LINKED ISSUE #58: 🐛🧑‍💻 - web Out of memory when trying to decompress a 17MB buffer
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Zstandard Web

### Which platforms are affected?

Web

### Description

Just trying to decompress a 17MB file, which should be decompressed into a 64MB one.

Here is the exception that I am getting:

```
Aborted(OOM)
RuntimeError: Aborted(OOM). Build with -sASSERTIONS for more info.
zstd.js 1:4611                                                                    abort
zstd.js 1:7164                                                                    abortOnCannotGrowMemory
zstd.js 1:7267                                                                    _emscripten_resize_heap
zstd.wasm 1:81863                                                                 50
zstd.wasm 1:127200                                                                84
zstd.js 1:7756                                                                    _malloc
zstd.js 32:32                                                                     decompressData
```

### Reproducing the issue

Just try to decompress a moderately large file.

### Flutter Version

3.25.3

### Relevant Log Output

```shell

```

### Flutter dependencies

_No response_

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by efraespada**
# 📌 Summary
- Fix web OOM when decompressing large buffers by enabling memory growth in the WebAssembly build and making the JS glue asynchronous and robust to module initialization order. This resolves an Aborted(OOM) scenario when decompressing around 17 MB inputs, bringing Web decompression in line with expected memory behavior.

---

## 🎯 Related Issues / Tickets
- Closes #58
- Related to #58 web decompression memory handling

---

## 🧩 Scope of Changes
- Added:
  - Memory growth options in the web build pipeline:
    - INITIAL_MEMORY, ALLOW_MEMORY_GROWTH, MAXIMUM_MEMORY in scripts/build_web_wasm.sh
  - Additional output path for the Zstandard web example to align with the expanded build outputs
  - Async/ready-state management for wasm module initialization in the JS glue code
- Updated:
  - Web glue and generated assets to support asynchronous module readiness and dynamic memory growth
  - zstandard_web integration tests to exercise roundtrip compression/decompression with updated API semantics
  - Multiple web artifacts (zstandard_web/blob/zstd.js, zstandard_web/example/web/zstd.js, and related outputs)
- Refactored:
  - compressData and decompressData wrappers to wait for wasm module readiness and to handle memory sizing more robustly (using Number() where appropriate)
  - Environment/loader logic to support modern JS runtimes (globalThis, robust locateFile resolution)
- Removed:
  - None explicitly; changes focus on memory management and async safety
- Added / Updated:
  - Integration tests for web context to cover roundtrip behavior after changes

---

## 🛠️ Technical Details
- Root cause and approach:
  - The previous web decompression path could trigger an out-of-memory condition when decompressing large buffers due to a non-growable heap and potential premature allocations.
  - The build now enables memory growth in the Emscripten-generated runtime:
    - INITIAL_MEMORY=134217728 (128 MB)
    - ALLOW_MEMORY_GROWTH=1
    - MAXIMUM_MEMORY=2147483648 (2 GB)
  - Glue code now ensures the wasm module is ready before performing compression/decompression, via a moduleReady Promise that resolves when Module.onRuntimeInitialized fires (or immediately if the module is already running).
  - Updated wrapper functions to be async; compressData and decompressData now return Promises and await module readiness, reducing risk of premature memory allocations and guaranteeing the memory is ready for operation.
  - Casts and memory calls updated to use Number(...) for sizes/returns to align with modern JS implementations.
- Key behavioral changes:
  - compressData and decompressData are now asynchronous; callers must await results.
  - Web outputs now include an additional zstandard example path reflecting the extended build outputs.
  - Memory management glue updated to better handle large decompression scenarios with growth enabled.

---

## 🔍 How to Test
1. Build the web artifacts with memory growth enabled:
   - Run: ./scripts/build_web_wasm.sh
2. Run the web integration tests:
   - In the Dart/Flutter web environment, run the web integration tests (updated to validate roundtrip compression/decompression).
   - Example: run the repository’s Dart/Flutter test commands that cover zstandard_web integration tests.
3. Manual/web sanity test:
   - Load the generated web assets in a browser (or run the Flutter web app) and perform a decompress of a ~17 MB buffer.
   - Verify that the decompressed size matches the expected ~64 MB and that the run completes without an OOM abort.
4. Validate test expectations:
   - Ensure the roundtrip test paths pass (compress then decompress yields original data).
   - Confirm no regressions in smaller payload paths.

---

## 🧪 Test Coverage
- [x] Integration tests
- [ ] Unit tests
- [ ] End-to-end (E2E) tests
- [ ] Manual testing only (explain why)
Notes: Integration tests for the web glue and the roundtrip behavior were updated to reflect the new async API and memory growth behavior.

---

## 📸 Screenshots / Recordings (UI changes only)
- None

---

## ⚠️ Breaking Changes
- [x] Breaking changes:
  - The web API surface for compression/decompression has changed to asynchronous calls. Callers must await results and adapt to Promise-based returns.
  - Memory management semantics now rely on growable heap; existing deployments that assumed fixed memory may behave differently until updated with the new build outputs.

---

## 🚀 Deployment Notes
- [x] No special deployment steps
- [ ] Requires database migration
- [ ] Requires environment variable changes
- [ ] Requires feature flag toggle
Details:
- Web assets and glue updated; ensure CI uses the updated build script and assets.
- No database or backend changes.

---

## 🔒 Security Considerations
- [ ] No security impact
- [ ] Input validation changes
- [ ] Authentication / authorization changes
- [ ] Sensitive data handling changes
Notes:
- No new security vulnerabilities introduced; memory growth should be constrained by the environment.

---

## 📈 Performance Impact
- [x] Improves performance
- [ ] No performance impact
- [ ] Potential performance regression (explain)
Notes:
- Memory growth enables handling larger inputs without failing from OOM, at the potential cost of larger peak memory on constrained devices. Overall, it prevents crashes and improves reliability for large buffers.

---

## 📝 Notes for Reviewers
- Review the changes to the wasm build script and the async glue to ensure all code paths properly await module readiness.
- Pay attention to the new memory flags and confirm they align with CI/browser targets used in this project.
- Verify that the integration tests cover the new async behavior and that the decompress path with large inputs completes without OOM.
- Consider whether any external callers need to adapt to the Promise-based API; update any downstream integrations accordingly.

---

## ✅ Checklist
- [x] I have self-reviewed my code
- [x] Code follows project standards and conventions
- [x] Tests have been added or updated
- [x] Documentation has been updated (if applicable)
- [x] No new warnings or lint errors
- [x] Changes are backward compatible or breaking changes are documented

---

## 📚 Additional Context
- This change brings Web decompression behavior in parity with the memory constraints commonly encountered on browsers and JavaScript runtimes by enabling growable memory and guarding against early allocations. The test suite and integration tests have been updated to reflect the new async API surface.

### CODE REVIEW

File: zstandard/example/web/zstd.js [hunk 1]
```diff
@@ -1,39 +1,58 @@
...
         outputBufferSize,
         inputPtr,
         inputData.length,
         compressionLevel
-    );
+    ));
 
     if (compressedSize < 0) {
         console.error('Compression error, error code: ', compressedSize);
+        Module._free(inputPtr);
```
Comment (vypbot) [inline zstandard/example/web/zstd.js]: ## getFrameContentSize error path handling

**Severity:** medium

**Location:** `zstandard/example/web/zstd.js:37`

getFrameContentSize may throw or fail; ensure errors are handled gracefully and memory is not leaked.
**Suggested fix:**
Improve error handling and ensure no memory leak; add tests for frame size errors.



<sup>Written by [vypdev/copilot](https://github.com/marketplace/actions/copilot-github-with-super-powers) for commit [68059dc6b0a3b3a778a48dc07e8d885902e876cd](https://github.com/vypdev/zstandard/commit/68059dc6b0a3b3a778a48dc07e8d885902e876cd). This will update automatically on new commits.</sup>
